coqui-ai/STT

README.rst
gitter link
Note: Without sub-def the next badge goes to the new line
=> Gitter room 

README.rst
=> Update README with DOI from Zenodo

doc/playbook/TRAINING.md
=> [docs playbook] fix a typo in TRAINING.md

training/coqui_stt_training/util/augmentations.py, training/coqui_stt_training/util/helpers.py
Added logging to augmentations.py and made some of the augmentation code more transparent in helpers.py and feeding.py
=> Add logging and clean up some augmentation code

notebooks/easy-transfer-learning.ipynb, notebooks/train-your-first-coqui-STT-model.ipynb, training/coqui_stt_training/train.py
for a cleaner, more intuitive python experience (especially in notebooks)
=> Move tfv1 calls inside high-level functions

.github/pull_request_template.md
Added CLA info to pull request template
=> Added CLA info to pull request template

doc/AUGMENTATION.rst, doc/BYTE_OUTPUT_MODE.rst, doc/COMMON_VOICE_DATA.rst, doc/DEPLOYMENT.rst, doc/EXPORTING_MODELS.rst, doc/LANGUAGE_MODEL.rst, doc/MIXED_PRECISION.rst, doc/TRAINING_ADVANCED.rst, doc/TRAINING_FLAGS.rst, doc/TRAINING_INTRO.rst, doc/TRANSFER_LEARNING.rst, doc/conf.py, doc/index.rst, doc/static/custom.css, train.py, training/coqui_stt_training/export.py, training/coqui_stt_training/train.py, training/coqui_stt_training/util/config.py
@JRMeyer could you take a look at the changes and read through the built docs? Thank you!
=> Documentation cleanup pass to match recent changes

native_client/python/client.py
=> Fix typo in clienty.py - shlex in line 17

doc/TRAINING_INTRO.rst
and I removed a character for the underline. :)
=> Fix typo virtual in documentation

bin/import_ccpmf.py
CCPMF extraction doesn’t work with zipfile. On python 3.6 one needs to use zipfile38 as zipfile.
```
root@a8772b2c0d74:/code# python bin/import_ccpmf.py /mnt/extracted/data/ccpmf/
2022-01-07 14:07:39.474588: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
WARNING: No --validate_label_locale specified, you might end with inconsistent dataset.
Source audio length: 1:40:54
Processing XML data: /mnt/extracted/data/ccpmf/transcriptionsXML_audioMP3_MEFR_CCPMF_2012-2020/2012/20120525_forum_am_latine_caraibes_1_copie_wmv_0_fre_minefi.xml
Progress |#################################################################### …
```
=> Fix CCPMF importer

.github/workflows/build-and-test.yml
=> Add support for Electron 16

bin/import_ts.py
Thanks to @lissyx, I can host the dataset on my kDrive. It's not perfect, but it will do for now as I don't have any other way to share a 28.5 Gb archive.
```bash
trainer@b65012d52dea:/io$ python bin/import_ts.py /mnt/extracted/data/TS
WARNING: No --validate_label_locale specified, you might end with inconsistent dataset.
No path "/mnt/extracted/data/TS" - creating ...
No archive "/mnt/extracted/data/TS/ts_2019-04-11_fr_FR.zip" - downloading...
0%|▏                                            | 44040192/30576634288 [00:26<3:48:01, 2231742.02it/s]
...
Found archive "/mnt/extracted/data/TrainingSpeech/ts_2019-04-11_fr_FR.zip" - not downloading.
No directory "/mnt/extracted/data/TrainingSpeech/ts_2019-04-11_fr_FR" - extracting archive...
Importing 124089 wav files...
Progress …
```
=> Bring back importer for TrainingSpeech

doc/.templates/page.html, doc/Makefile, doc/requirements.txt
Preview: https://stt--jina-docs.netlify.app/
=> Add docqa to docs website

native_client/dotnet/STTClient/Extensions/NativeExtensions.cs, native_client/dotnet/STTClient/Interfaces/ISTT.cs, native_client/dotnet/STTClient/STT.cs, native_client/dotnet/STTClient/STTClient.csproj
.Net client build was broken. 
Switch to .net standard for broader compatibility.
=> Fix .net build

doc/BUILDING.rst
Just updated the bazel version in the docs.  I did sign the contributor agreement, and ran the pre-commit hook.
=> update bazel version in docs (fixes #2190)

doc/playbook/ENVIRONMENT.md
=> Update nvidia-container-toolkit setup documentation

.github/workflows/build-and-test.yml, native_client/BUILD
=> Use TFLite 2.9

.github/workflows/build-and-test.yml, ci_scripts/package-utils.sh, ci_scripts/package.sh, ci_scripts/wasm-build.sh, ci_scripts/wasm-package.sh, native_client/BUILD, native_client/wasm/bindings.cc
I polished this over the weekend and I believe we're getting closer to being merge-able!
This requires coqui-ai/tensorflow#12 to be merged to build properly.
Things to do:
This [Contributor License …
=> Compile STT to WASM

doc/DEPLOYMENT.rst, doc/NodeJS-API.rst
=> Add the wasm docs

doc/playbook/ENVIRONMENT.md
=> updating docker tag to latest in environment setup docs

native_client/args.h, native_client/client.cc, native_client/coqui-stt.h, native_client/ctcdecode/output.h, native_client/ctcdecode/path_trie.cpp, native_client/modelstate.cc, native_client/stt.cc
Follow up to #2075, and #2340, to return the model outputs to the user.
=> Getting logits to the client code
