coqui-ai/STT

doc/BUILDING.rst

Using custom swig should not be necessary to build ctcdecoder on x86 and also ppc64le architecture anymore.
I think the reference was missed to be replaced in the docu.

Stop pointing people to a fork for docs on building SWIG

---

native_client/swift/stt_ios_test.xcodeproj/project.pbxproj

Removes `libstt.so` reference from stt_ios_test project because it is not needed because all dependency comes from the framework.
Fixes #1875

Remove libstt.so reference from stt_ios_test project

---

native_client/BUILD

This changes the name of the ios framework to `stt_ios` to be compatible with the naming that is used in the Xcode projects. Currently you have to manually rename the framework after building it. Alternatively we could change the names in the Xcode projects to `coqui_stt_ios`.
We would also need to change the name in the taskcluster command but that seems to not be touched anymore.

Change static ios framework name to stt_ios from coqui_stt_ios

---

Dockerfile.train

Use NVIDIA's tensorflow docker image as base for training `Dockerfile.train`. Former image from Tensorflow caused issues on AWS A100 cluster (p4d.24xlarge)

Use NVIDIA image in Dockerfile

---

setup.py
training/coqui_stt_training/util/downloader.py

This changes only the progressbar in `maybe_download`, which is blocking our jupyter notebooks from working. Changing all progressbars to tqdm will take more time.

Change progressbar to tqdm

---

Dockerfile.build
doc/DEPLOYMENT.rst

Make Dockerfile.build copy the current checked out source code into the Docker image instead of downloading a fresh clone.
This was useful to me, saved time and effort and allowed me to easily build the specific tag / commit that I was working on at the time.

Fix #1955 Use local source instead of redownloading in Dockerfile.build

---

native_client/swift/stt_ios/STT.swift

We changed from `STTStream.finishStream` to `STTStream.finishStreamWithMetadata` and started to experience `EXC_BAD_ACCESS` errors.
```
0   stt_ios                       	0x00000001065fb4dc DecoderState::~DecoderState() + 88
1   stt_ios                       	0x00000001065f9a14 StreamingState::~StreamingState() + 24
2   stt_ios                       	0x00000001065fb230 STT_FreeStream + 16
3   stt_ios                       	0x00000001065f870c STTStream.deinit + 12 (STT.swift:185)
4   stt_ios                       	0x00000001065f870c STTStream.__deallocating_deinit + 20 (STT.swift:183)
```
After long debugging I found out, that this is caused by a duplicate call of `STT_FreeStream`.
`STTStream.finishStreamWithMetadata` does not unset streamCtx, so the destructor of STTStream calles …

fixed duplicate deallocation of stream in Swift STTStream

---

ci_scripts/asserts.sh
native_client/coqui-stt.h
native_client/javascript/client.ts
native_client/javascript/index.ts
native_client/javascript/stt.i
native_client/python/__init__.py
native_client/python/impl.i
native_client/stt.cc
native_client/tflitemodelstate.cc

This flushes the buffer through the acoustic model before returning
an intermediate decode. Provides an alternative to finishStream()
that doesn't end the stream.
Fixes #1953
I added the Python bindings manually, as I haven't used SWIG before. Let me know there's any glaring mistakes. I haven't added any other bindings so if you have any pointers on how to do that I will happily oblige.
Let me know if there's anything else that needs changing!
The function seems to be working very well on our test hardware and is improving command response with the unreliable webrtc VAD a great deal!
Built and tested on v0.10.0-alpha.9 because I couldn't get later versions to compile.

Add intermediateDecodeExpensive() function and Python binding

---

bin/import_atthack.py
bin/import_ccpmf.py
bin/import_m-ailabs.py
bin/import_mls.py
bin/import_slr57.py

This is not usefull for every importer, but sometimes we leave a lot of sentences aside because they are too long.
What we can do with this data is to use it to build our scorer, hence the need to save them to disk when we exclude them at import time.
See #2092 for context.

Add excluded sentences to LM

---

native_client/ctcdecode/__init__.py
training/coqui_stt_training/evaluate.py
training/coqui_stt_training/training_graph_inference.py

Currently we're discarding everything but confidence and transcript.

Expose raw tokens and timesteps in decoder Python package

---

setup.py

[webdataset silently broke compatibility with Python 3.6 and 3.7 on the latest release](https://github.com/webdataset/webdataset/issues/166)

Pin webdataset requirement for Python 3.7 compat (Fixes #2168)

---

Dockerfile.train
setup.py
training/coqui_stt_training/export.py

This PR makes available a new `venv` using `python3.7` to export your checkpoints to the TFLite format.
Instead of using the image' system python (3.8), use python 3.7 from venv at `/tflite-venv/bin/python`.
```bash
root@65576a3b3080:/code# /tflite-venv/bin/python -m coqui_stt_training.export --alphabet_config_path /mnt/models/alphabet.txt --scorer_path /mnt/lm/kenlm.scorer --feature_cache /mnt/sources/feature_cache --n_hidden 2048 --beam_width 500 --lm_alpha 1.6383103526118539 --lm_beta 0.1291025653672666 --load_evaluate best --checkpoint_dir /mnt/checkpoints/ --export_dir /mnt/models/ --export_tflite true --export_author_id CommonVoice-FR-Team --export_model_version 0.9 --export_contact_info https://discourse.mozilla.org/c/voice/fr --export_license MIT-0 --export_language fr-FR …
```

export to tflite using python37 venv

---

.github/workflows/build-and-test.yml

The mentioned workflow is failing due to the used image changing the default Android NDK version from 21 to 23. This attempts to force the use of NDK 19c, which is what is currently being used to build the libs: https://github.com/coqui-ai/STT/blob/922fe39eadab6e5e5c6384c4f5b93adb38b815c1/ci_scripts/tf-vars.sh#L19-L20
Before accepting your …

Fix Android AAR+APK build on CI

---

ci_scripts/wasm-build.sh

Since emsdk and bazel caching do not play well together, we need to explicitly pass in the PATH to bazel, so that it picks up the right version of python3
This [Contributor License …

Use the correct python when building Wasm

---

native_client/definitions.mk

This PR updates the ds-swig release URLs in the definitions.mk file to the latest ds-swig in coqui STT v1.3.0.
Without updating these URLs, building swig dependant bindings would throw the following error: `error: macro "SWIGV8_ARRAY_NEW" passed 1 arguments, but takes just 0.`. This issue came up in another [draft PR](https://github.com/coqui-ai/STT/pull/2269), which may provide more insight.
These changes were tested on linux, so any help testing them on other OSs would be greatly appreciated.
I am afraid the changes in this PR don't account for ARM architectures, whose ds-swig releases are available for download on v1.3.0 and were not availble back in DS v0.9.3. I am not sure how to add support to that, so any insights would be appreciated.

Update ds-swig release URLs

---

native_client/javascript/index.ts
native_client/javascript/stt.i

This PR allows loading models from buffer for the nodejs bindings. 
Some important remarks:
1. I am not very familiar with SWIG, so it would be nice to have someone that is reviewing these changes.
2. I tried to keep aModelData as a string to avoid the multiple allowed types, but converting the string back to an UInt8Array would provide different results. Could we keep the UInt8Array as an allowed input type?

Allow loading model from buffer in nodejs

---

setup.py

Using bmcfee/resampy in version 0.3.X produces issue #2268 This should be fixed resampy 0.4.0.
I suggest to require resampy  0.4 instead of old 0.2.2

Resampy 0.4.0

---

.github/workflows/build-and-test.yml

This PR fixes the following error on the CI "Mac|Build libstt+client (arm64)" step:
```Error: Invalid formula: /Users/runner/arm-target/arm-brew/Library/Taps/homebrew/homebrew-core/Formula/mit-scheme.rb mit-scheme: undefined method `on_intel' for #<Resource:0x00007fa8b537fc98>```
This error is fixed by updating brew to the latest version, 3.5.9.

Update brew to v3.5.9 to fix mac arm64 build

---

README.rst

As a total newb to coqui-ai/stt and STT en general I was surprised that the quickstart wasn't easier to find.  I'm proposing adding this link so others will find it faster.
This [Contributor License …

Adds direct link to quickstart

---

native_client/generate_scorer_package.cpp

Addresses https://github.com/coqui-ai/STT/issues/2329
```
generate_scorer_package --lm /mnt/lm/lm.binary --vocab /mnt/lm/vocab-500000.txt --package /mnt/lm/kenlm.scorer --default_alpha 0 --default_beta 0
500000 unique words read from vocabulary file.
Doesn't look like a character based (Bytes Are All You Need) model.
--force_bytes_output_mode was not specified, using value infered from vocabulary contents: false
No --checkpoint file specified, not using bytes output mode, can't continue.
Checkpoint path must contains an alphabet.
Start by creating an alphabet for your models using coqui_stt_training.util.check_characters if needed.
python -m coqui_stt_training.util.check_characters \
--csv-files ... \
--alphabet-format | grep -v '^#' | sort -n > models/alphabet.txt
This will create an …
```

Updated missing checkpoint path error message

---

.github/actions/get_cache_key/action.yml
.github/actions/numpy_vers/action.yml
.github/actions/win-numpy-vers/action.yml
.github/workflows/build-and-test.yml
.github/workflows/lint.yml

A PR to fix the errors in the latest builds and fix warnings that might cause issues
Update Brew to 3.6.21 to fix Mac build issue
Update Build AAR+APK to use JDK 11 to build the build issue, related to https://github.com/android-actions/setup-android/issues/378 
Update various actions to v3 or v4 to resolve usage of node12, related to https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Update set-output calls to echo to GITHUB_OUTPUT, related to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. The only set-output in the actions that I haven't changed is in check_artifact_exists\dist\index.js since I don't know how to change it.
Builds in my fork works.

Fixes for warnings and errors in the build.
